env:
  es2021: true
  node: true
extends: 
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  eqeqeq:
    - error
  no-else-return:
    - error
  no-useless-catch:
    - error
  eol-last: 
    - error
    - always
  curly:
    - error
  no-return-await:
    - error
  require-await:
    - warn
